import { ThemeConfig } from '../types';

export const minimalismTheme: ThemeConfig = {
  name: 'minimalism',
  colors: {
    primary: '2E5E7E',
    primaryDark: '1F3A5F',
    primaryLight: 'E4EDF3',
    secondary: '2F7D5E',
    secondaryLight: 'E3F0EA',
    accent: 'C0392B',
    accentLight: 'F7E4E1',
    danger: 'C0392B',
    dangerLight: 'F7E4E1',
    success: '2F7D5E',
    successLight: 'E3F0EA',
    cyan: '0F9ED5',
    purple: 'A02B93',
    lightGreen: '4EA72E',
    orange: 'C87A2C',
    dark: '1B2A3A',
    textGray: '5A6B7C',
    medium: '5A6B7C',
    light: 'F1EDE2',
    surface: 'FFFDF7',
    codeBg: '17293D',
    white: 'FFFFFF',
    border: 'DDD6C6',
    boxBorder: 'D5CDBB',
  },
  fonts: {
    title: 'Segoe UI',
    body: 'Segoe UI',
    code: 'Consolas',
  },
  background: 'FBF9F2',
  slideWidth: 13.33,
  slideHeight: 7.5,
  header: {
    style: 'minimal',
    titlePosition: { x: 1.83, y: 0.2, w: 11.0, h: 0.52 },
    fontSize: 27,
  },
  footer: {
    style: 'line',
  },
  logo: {
    paths: [
      '../assets/fpt_logo.png',
      '../../slides/assets/fpt_logo.png',
      'assets/fpt_logo.png',
    ],
    small: { x: 0.2, y: 0.15, w: 1.5, h: 0.58 },
    large: { x: 0.4, y: 0.3, w: 2.36, h: 0.92 },
  },
  boxStyle: 'semi-transparent',
};
